[workspace]
name = "pixi-uv-cuda-template"
version = "0.1.0"
channels = ["conda-forge"]
platforms = [{ platform = "linux-64", cuda = "12.4" }]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
torch = { version = "==2.4.1", index = "https://download.pytorch.org/whl/cu124" }

[tasks]
check-gpu = "python scripts/check_cuda.py"
